FROM node:22-alpine

WORKDIR /app

COPY package*.json .
RUN npm ci --force
COPY healthcheck.js healthcheck.js
COPY src src

ENV PORT=3000

# HOT reload
ENV CHOKIDAR_USEPOLLING=true
ENV WATCHPACK_POLLING=true

CMD ["npm", "run", "dev"]
